// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/error.dart';
import 'api/groups.dart';
import 'api/identity.dart';
import 'api/init.dart';
import 'api/key_packages.dart';
import 'api/media.dart';
import 'api/messages.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'state.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CreateGroupParams dco_decode_box_autoadd_create_group_params(dynamic raw);

  @protected
  GroupMetadataUpdate dco_decode_box_autoadd_group_metadata_update(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  MarmotGroup dco_decode_box_autoadd_marmot_group(dynamic raw);

  @protected
  MarmotMessage dco_decode_box_autoadd_marmot_message(dynamic raw);

  @protected
  MediaRefInput dco_decode_box_autoadd_media_ref_input(dynamic raw);

  @protected
  MessageListParams dco_decode_box_autoadd_message_list_params(dynamic raw);

  @protected
  StorageConfig dco_decode_box_autoadd_storage_config(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CreateGroupParams dco_decode_create_group_params(dynamic raw);

  @protected
  EncryptedMediaOutput dco_decode_encrypted_media_output(dynamic raw);

  @protected
  GroupCreateResult dco_decode_group_create_result(dynamic raw);

  @protected
  GroupImagePrepared dco_decode_group_image_prepared(dynamic raw);

  @protected
  GroupMetadataUpdate dco_decode_group_metadata_update(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KeyPackageEventData dco_decode_key_package_event_data(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw);

  @protected
  List<MarmotGroup> dco_decode_list_marmot_group(dynamic raw);

  @protected
  List<MarmotMediaRef> dco_decode_list_marmot_media_ref(dynamic raw);

  @protected
  List<MarmotMember> dco_decode_list_marmot_member(dynamic raw);

  @protected
  List<MarmotMessage> dco_decode_list_marmot_message(dynamic raw);

  @protected
  List<PendingWelcome> dco_decode_list_pending_welcome(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MarmotError dco_decode_marmot_error(dynamic raw);

  @protected
  MarmotGroup dco_decode_marmot_group(dynamic raw);

  @protected
  MarmotMediaRef dco_decode_marmot_media_ref(dynamic raw);

  @protected
  MarmotMember dco_decode_marmot_member(dynamic raw);

  @protected
  MarmotMessage dco_decode_marmot_message(dynamic raw);

  @protected
  MediaRefInput dco_decode_media_ref_input(dynamic raw);

  @protected
  MemberChangeResult dco_decode_member_change_result(dynamic raw);

  @protected
  MessageListParams dco_decode_message_list_params(dynamic raw);

  @protected
  NostrKeypair dco_decode_nostr_keypair(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  MarmotGroup? dco_decode_opt_box_autoadd_marmot_group(dynamic raw);

  @protected
  MarmotMessage? dco_decode_opt_box_autoadd_marmot_message(dynamic raw);

  @protected
  MessageListParams? dco_decode_opt_box_autoadd_message_list_params(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PendingWelcome dco_decode_pending_welcome(dynamic raw);

  @protected
  StorageConfig dco_decode_storage_config(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CreateGroupParams sse_decode_box_autoadd_create_group_params(
    SseDeserializer deserializer,
  );

  @protected
  GroupMetadataUpdate sse_decode_box_autoadd_group_metadata_update(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MarmotGroup sse_decode_box_autoadd_marmot_group(SseDeserializer deserializer);

  @protected
  MarmotMessage sse_decode_box_autoadd_marmot_message(
    SseDeserializer deserializer,
  );

  @protected
  MediaRefInput sse_decode_box_autoadd_media_ref_input(
    SseDeserializer deserializer,
  );

  @protected
  MessageListParams sse_decode_box_autoadd_message_list_params(
    SseDeserializer deserializer,
  );

  @protected
  StorageConfig sse_decode_box_autoadd_storage_config(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CreateGroupParams sse_decode_create_group_params(
    SseDeserializer deserializer,
  );

  @protected
  EncryptedMediaOutput sse_decode_encrypted_media_output(
    SseDeserializer deserializer,
  );

  @protected
  GroupCreateResult sse_decode_group_create_result(
    SseDeserializer deserializer,
  );

  @protected
  GroupImagePrepared sse_decode_group_image_prepared(
    SseDeserializer deserializer,
  );

  @protected
  GroupMetadataUpdate sse_decode_group_metadata_update(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KeyPackageEventData sse_decode_key_package_event_data(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer);

  @protected
  List<MarmotGroup> sse_decode_list_marmot_group(SseDeserializer deserializer);

  @protected
  List<MarmotMediaRef> sse_decode_list_marmot_media_ref(
    SseDeserializer deserializer,
  );

  @protected
  List<MarmotMember> sse_decode_list_marmot_member(
    SseDeserializer deserializer,
  );

  @protected
  List<MarmotMessage> sse_decode_list_marmot_message(
    SseDeserializer deserializer,
  );

  @protected
  List<PendingWelcome> sse_decode_list_pending_welcome(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MarmotError sse_decode_marmot_error(SseDeserializer deserializer);

  @protected
  MarmotGroup sse_decode_marmot_group(SseDeserializer deserializer);

  @protected
  MarmotMediaRef sse_decode_marmot_media_ref(SseDeserializer deserializer);

  @protected
  MarmotMember sse_decode_marmot_member(SseDeserializer deserializer);

  @protected
  MarmotMessage sse_decode_marmot_message(SseDeserializer deserializer);

  @protected
  MediaRefInput sse_decode_media_ref_input(SseDeserializer deserializer);

  @protected
  MemberChangeResult sse_decode_member_change_result(
    SseDeserializer deserializer,
  );

  @protected
  MessageListParams sse_decode_message_list_params(
    SseDeserializer deserializer,
  );

  @protected
  NostrKeypair sse_decode_nostr_keypair(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MarmotGroup? sse_decode_opt_box_autoadd_marmot_group(
    SseDeserializer deserializer,
  );

  @protected
  MarmotMessage? sse_decode_opt_box_autoadd_marmot_message(
    SseDeserializer deserializer,
  );

  @protected
  MessageListParams? sse_decode_opt_box_autoadd_message_list_params(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PendingWelcome sse_decode_pending_welcome(SseDeserializer deserializer);

  @protected
  StorageConfig sse_decode_storage_config(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_create_group_params(
    CreateGroupParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_group_metadata_update(
    GroupMetadataUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_marmot_group(
    MarmotGroup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_marmot_message(
    MarmotMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_media_ref_input(
    MediaRefInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_message_list_params(
    MessageListParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_storage_config(
    StorageConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_create_group_params(
    CreateGroupParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_encrypted_media_output(
    EncryptedMediaOutput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_create_result(
    GroupCreateResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_image_prepared(
    GroupImagePrepared self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_group_metadata_update(
    GroupMetadataUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_key_package_event_data(
    KeyPackageEventData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_marmot_group(
    List<MarmotGroup> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_marmot_media_ref(
    List<MarmotMediaRef> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_marmot_member(
    List<MarmotMember> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_marmot_message(
    List<MarmotMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pending_welcome(
    List<PendingWelcome> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_marmot_error(MarmotError self, SseSerializer serializer);

  @protected
  void sse_encode_marmot_group(MarmotGroup self, SseSerializer serializer);

  @protected
  void sse_encode_marmot_media_ref(
    MarmotMediaRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_marmot_member(MarmotMember self, SseSerializer serializer);

  @protected
  void sse_encode_marmot_message(MarmotMessage self, SseSerializer serializer);

  @protected
  void sse_encode_media_ref_input(MediaRefInput self, SseSerializer serializer);

  @protected
  void sse_encode_member_change_result(
    MemberChangeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_list_params(
    MessageListParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nostr_keypair(NostrKeypair self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_marmot_group(
    MarmotGroup? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_marmot_message(
    MarmotMessage? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_message_list_params(
    MessageListParams? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pending_welcome(
    PendingWelcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_storage_config(StorageConfig self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
