// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'state.freezed.dart';

@freezed
sealed class StorageConfig with _$StorageConfig {
  const StorageConfig._();

  /// In-memory storage (testing / ephemeral). Requires `test-utils` feature.
  const factory StorageConfig.memory() = StorageConfig_Memory;

  /// Automatic SQLite storage. Host must call `initKeyringStore()` first.
  const factory StorageConfig.sqlite({
    required String dbPath,
    required String serviceId,
    required String keyId,
  }) = StorageConfig_Sqlite;

  /// Manual SQLite storage. Host supplies a 32-byte encryption key directly.
  const factory StorageConfig.sqliteWithKey({
    required String dbPath,
    required Uint8List dbKey,
  }) = StorageConfig_SqliteWithKey;
}
