// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`, `from`

@freezed
sealed class MarmotError with _$MarmotError implements FrbException {
  const MarmotError._();

  const factory MarmotError.notInitialised() = MarmotError_NotInitialised;
  const factory MarmotError.noIdentity() = MarmotError_NoIdentity;
  const factory MarmotError.invalidNsec() = MarmotError_InvalidNsec;
  const factory MarmotError.invalidPublicKey() = MarmotError_InvalidPublicKey;
  const factory MarmotError.invalidRelayUrl(String field0) =
      MarmotError_InvalidRelayUrl;
  const factory MarmotError.invalidEvent(String field0) =
      MarmotError_InvalidEvent;
  const factory MarmotError.groupNotFound() = MarmotError_GroupNotFound;
  const factory MarmotError.welcomeNotFound() = MarmotError_WelcomeNotFound;
  const factory MarmotError.notAdmin() = MarmotError_NotAdmin;
  const factory MarmotError.keyring(String field0) = MarmotError_Keyring;
  const factory MarmotError.unsupported(String field0) =
      MarmotError_Unsupported;
  const factory MarmotError.lock() = MarmotError_Lock;
  const factory MarmotError.media(String field0) = MarmotError_Media;
  const factory MarmotError.mdk(String field0) = MarmotError_Mdk;
}
