// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bytes_to_array`, `group_dto`, `member_change_dto`

Future<GroupCreateResult> create({
  required String dbPath,
  required String creatorNpub,
  required CreateGroupParams params,
}) => RustLib.instance.api.crateApiGroupsCreate(
  dbPath: dbPath,
  creatorNpub: creatorNpub,
  params: params,
);

Future<void> processWelcome({
  required String dbPath,
  required String wrapperEventId,
  required String welcomeRumorJson,
}) => RustLib.instance.api.crateApiGroupsProcessWelcome(
  dbPath: dbPath,
  wrapperEventId: wrapperEventId,
  welcomeRumorJson: welcomeRumorJson,
);

Future<List<PendingWelcome>> getPendingWelcomes({required String dbPath}) =>
    RustLib.instance.api.crateApiGroupsGetPendingWelcomes(dbPath: dbPath);

Future<void> acceptWelcome({
  required String dbPath,
  required String welcomeId,
}) => RustLib.instance.api.crateApiGroupsAcceptWelcome(
  dbPath: dbPath,
  welcomeId: welcomeId,
);

Future<List<MarmotGroup>> list({required String dbPath}) =>
    RustLib.instance.api.crateApiGroupsList(dbPath: dbPath);

Future<List<MarmotMember>> getMembers({
  required String dbPath,
  required String groupId,
}) => RustLib.instance.api.crateApiGroupsGetMembers(
  dbPath: dbPath,
  groupId: groupId,
);

Future<MemberChangeResult> addMember({
  required String dbPath,
  required String groupId,
  required String keyPackageEventJson,
}) => RustLib.instance.api.crateApiGroupsAddMember(
  dbPath: dbPath,
  groupId: groupId,
  keyPackageEventJson: keyPackageEventJson,
);

Future<MemberChangeResult> removeMember({
  required String dbPath,
  required String groupId,
  required String npub,
}) => RustLib.instance.api.crateApiGroupsRemoveMember(
  dbPath: dbPath,
  groupId: groupId,
  npub: npub,
);

Future<String> updateGroupMetadata({
  required String dbPath,
  required String groupId,
  required GroupMetadataUpdate update,
}) => RustLib.instance.api.crateApiGroupsUpdateGroupMetadata(
  dbPath: dbPath,
  groupId: groupId,
  update: update,
);

Future<GroupImagePrepared> prepareGroupImage({
  required List<int> imageData,
  required String mimeType,
}) => RustLib.instance.api.crateApiGroupsPrepareGroupImage(
  imageData: imageData,
  mimeType: mimeType,
);

Future<String> setGroupImage({
  required String dbPath,
  required String groupId,
  required List<int> imageHash,
  required List<int> imageKey,
  required List<int> imageNonce,
  required List<int> imageUploadKey,
}) => RustLib.instance.api.crateApiGroupsSetGroupImage(
  dbPath: dbPath,
  groupId: groupId,
  imageHash: imageHash,
  imageKey: imageKey,
  imageNonce: imageNonce,
  imageUploadKey: imageUploadKey,
);

Future<String> clearGroupImage({
  required String dbPath,
  required String groupId,
}) => RustLib.instance.api.crateApiGroupsClearGroupImage(
  dbPath: dbPath,
  groupId: groupId,
);

/// Remove self from a group via MLS. Returns the commit event JSON to publish
/// to the group's relays. Admins must self-demote before leaving.
Future<MemberChangeResult> leaveGroup({
  required String dbPath,
  required String groupId,
}) => RustLib.instance.api.crateApiGroupsLeaveGroup(
  dbPath: dbPath,
  groupId: groupId,
);

/// Delete all locally stored messages for a group. The group remains active and
/// can receive new messages. Returns the number of messages deleted.
/// Local-only — no events published.
Future<BigInt> deleteMessagesForGroup({
  required String dbPath,
  required String groupId,
}) => RustLib.instance.api.crateApiGroupsDeleteMessagesForGroup(
  dbPath: dbPath,
  groupId: groupId,
);

/// Delete ALL local state for a group: messages, MLS tree, keys, relays,
/// proposals, snapshots. The group cannot receive new messages afterward.
/// Call [leave_group] first to notify other members. Idempotent.
/// Local-only — no events published.
Future<void> deleteGroup({required String dbPath, required String groupId}) =>
    RustLib.instance.api.crateApiGroupsDeleteGroup(
      dbPath: dbPath,
      groupId: groupId,
    );

Future<Uint8List> decryptGroupImageBlob({
  required List<int> encryptedData,
  required List<int> imageHash,
  required List<int> imageKey,
  required List<int> imageNonce,
}) => RustLib.instance.api.crateApiGroupsDecryptGroupImageBlob(
  encryptedData: encryptedData,
  imageHash: imageHash,
  imageKey: imageKey,
  imageNonce: imageNonce,
);

class CreateGroupParams {
  final String name;
  final String description;
  final List<String> relayUrls;
  final List<String> memberKeyPackageEventJsons;

  const CreateGroupParams({
    required this.name,
    required this.description,
    required this.relayUrls,
    required this.memberKeyPackageEventJsons,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      relayUrls.hashCode ^
      memberKeyPackageEventJsons.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateGroupParams &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          relayUrls == other.relayUrls &&
          memberKeyPackageEventJsons == other.memberKeyPackageEventJsons;
}

class GroupCreateResult {
  final MarmotGroup group;
  final List<String> welcomeRumors;

  const GroupCreateResult({required this.group, required this.welcomeRumors});

  @override
  int get hashCode => group.hashCode ^ welcomeRumors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupCreateResult &&
          runtimeType == other.runtimeType &&
          group == other.group &&
          welcomeRumors == other.welcomeRumors;
}

class GroupImagePrepared {
  final Uint8List encryptedData;
  final Uint8List imageHash;
  final Uint8List imageKey;
  final Uint8List imageNonce;
  final Uint8List imageUploadKey;
  final String uploadNsec;
  final String uploadPubkeyHex;
  final String mimeType;
  final String? blurhash;
  final String? thumbhash;
  final int? dimensionsWidth;
  final int? dimensionsHeight;

  const GroupImagePrepared({
    required this.encryptedData,
    required this.imageHash,
    required this.imageKey,
    required this.imageNonce,
    required this.imageUploadKey,
    required this.uploadNsec,
    required this.uploadPubkeyHex,
    required this.mimeType,
    this.blurhash,
    this.thumbhash,
    this.dimensionsWidth,
    this.dimensionsHeight,
  });

  @override
  int get hashCode =>
      encryptedData.hashCode ^
      imageHash.hashCode ^
      imageKey.hashCode ^
      imageNonce.hashCode ^
      imageUploadKey.hashCode ^
      uploadNsec.hashCode ^
      uploadPubkeyHex.hashCode ^
      mimeType.hashCode ^
      blurhash.hashCode ^
      thumbhash.hashCode ^
      dimensionsWidth.hashCode ^
      dimensionsHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupImagePrepared &&
          runtimeType == other.runtimeType &&
          encryptedData == other.encryptedData &&
          imageHash == other.imageHash &&
          imageKey == other.imageKey &&
          imageNonce == other.imageNonce &&
          imageUploadKey == other.imageUploadKey &&
          uploadNsec == other.uploadNsec &&
          uploadPubkeyHex == other.uploadPubkeyHex &&
          mimeType == other.mimeType &&
          blurhash == other.blurhash &&
          thumbhash == other.thumbhash &&
          dimensionsWidth == other.dimensionsWidth &&
          dimensionsHeight == other.dimensionsHeight;
}

class GroupMetadataUpdate {
  final String? name;
  final String? description;
  final List<String>? relayUrls;
  final List<String>? adminNpubs;

  const GroupMetadataUpdate({
    this.name,
    this.description,
    this.relayUrls,
    this.adminNpubs,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      relayUrls.hashCode ^
      adminNpubs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GroupMetadataUpdate &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          relayUrls == other.relayUrls &&
          adminNpubs == other.adminNpubs;
}

class MarmotGroup {
  final String id;
  final String nostrGroupId;
  final String name;
  final String description;
  final List<String> relayUrls;
  final List<String> adminNpubs;
  final int memberCount;
  final Uint8List? imageHash;
  final Uint8List? imageKey;
  final Uint8List? imageNonce;
  final String? lastMessageId;
  final PlatformInt64? lastMessageAtSecs;
  final PlatformInt64? lastMessageProcessedAtSecs;

  const MarmotGroup({
    required this.id,
    required this.nostrGroupId,
    required this.name,
    required this.description,
    required this.relayUrls,
    required this.adminNpubs,
    required this.memberCount,
    this.imageHash,
    this.imageKey,
    this.imageNonce,
    this.lastMessageId,
    this.lastMessageAtSecs,
    this.lastMessageProcessedAtSecs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      nostrGroupId.hashCode ^
      name.hashCode ^
      description.hashCode ^
      relayUrls.hashCode ^
      adminNpubs.hashCode ^
      memberCount.hashCode ^
      imageHash.hashCode ^
      imageKey.hashCode ^
      imageNonce.hashCode ^
      lastMessageId.hashCode ^
      lastMessageAtSecs.hashCode ^
      lastMessageProcessedAtSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarmotGroup &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          nostrGroupId == other.nostrGroupId &&
          name == other.name &&
          description == other.description &&
          relayUrls == other.relayUrls &&
          adminNpubs == other.adminNpubs &&
          memberCount == other.memberCount &&
          imageHash == other.imageHash &&
          imageKey == other.imageKey &&
          imageNonce == other.imageNonce &&
          lastMessageId == other.lastMessageId &&
          lastMessageAtSecs == other.lastMessageAtSecs &&
          lastMessageProcessedAtSecs == other.lastMessageProcessedAtSecs;
}

class MarmotMember {
  final String npub;
  final String pubkeyHex;

  const MarmotMember({required this.npub, required this.pubkeyHex});

  @override
  int get hashCode => npub.hashCode ^ pubkeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarmotMember &&
          runtimeType == other.runtimeType &&
          npub == other.npub &&
          pubkeyHex == other.pubkeyHex;
}

class MemberChangeResult {
  final String evolutionEventJson;
  final List<String> welcomeRumors;

  const MemberChangeResult({
    required this.evolutionEventJson,
    required this.welcomeRumors,
  });

  @override
  int get hashCode => evolutionEventJson.hashCode ^ welcomeRumors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberChangeResult &&
          runtimeType == other.runtimeType &&
          evolutionEventJson == other.evolutionEventJson &&
          welcomeRumors == other.welcomeRumors;
}

class PendingWelcome {
  final String id;
  final String groupName;
  final String inviterNpub;
  final int memberCount;

  const PendingWelcome({
    required this.id,
    required this.groupName,
    required this.inviterNpub,
    required this.memberCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      groupName.hashCode ^
      inviterNpub.hashCode ^
      memberCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingWelcome &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          groupName == other.groupName &&
          inviterNpub == other.inviterNpub &&
          memberCount == other.memberCount;
}
