// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `keypair_with_secret`

/// Generate a new Nostr keypair. Pure function — no MDK state needed.
Future<NostrKeypair> generate() =>
    RustLib.instance.api.crateApiIdentityGenerate();

/// Parse nsec and return the full keypair. Pure function — no MDK state needed.
Future<NostrKeypair> importFromNsec({required String nsec}) =>
    RustLib.instance.api.crateApiIdentityImportFromNsec(nsec: nsec);

Future<bool> validateNsec({required String nsec}) =>
    RustLib.instance.api.crateApiIdentityValidateNsec(nsec: nsec);

Future<String> npubFromNsec({required String nsec}) =>
    RustLib.instance.api.crateApiIdentityNpubFromNsec(nsec: nsec);

/// Convert a bech32 npub to its hex representation. Used for Nostr relay filters.
Future<String> pubkeyHexFromNpub({required String npub}) =>
    RustLib.instance.api.crateApiIdentityPubkeyHexFromNpub(npub: npub);

class NostrKeypair {
  final String npub;
  final String? nsec;
  final String pubkeyHex;

  const NostrKeypair({required this.npub, this.nsec, required this.pubkeyHex});

  @override
  int get hashCode => npub.hashCode ^ nsec.hashCode ^ pubkeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NostrKeypair &&
          runtimeType == other.runtimeType &&
          npub == other.npub &&
          nsec == other.nsec &&
          pubkeyHex == other.pubkeyHex;
}
