// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../state.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initKeyringStore() =>
    RustLib.instance.api.crateApiInitInitKeyringStore();

Future<void> initMdk({
  required String dbPath,
  required StorageConfig storage,
}) =>
    RustLib.instance.api.crateApiInitInitMdk(dbPath: dbPath, storage: storage);

Future<void> removeSession({required String dbPath}) =>
    RustLib.instance.api.crateApiInitRemoveSession(dbPath: dbPath);
