// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<KeyPackageEventData> create({
  required String dbPath,
  required String npub,
  required List<String> relayUrls,
}) => RustLib.instance.api.crateApiKeyPackagesCreate(
  dbPath: dbPath,
  npub: npub,
  relayUrls: relayUrls,
);

Future<String> createSignedEvent({
  required String dbPath,
  required String nsec,
  required List<String> relayUrls,
}) => RustLib.instance.api.crateApiKeyPackagesCreateSignedEvent(
  dbPath: dbPath,
  nsec: nsec,
  relayUrls: relayUrls,
);

Future<String> signEvent({
  required String nsec,
  required String unsignedEventJson,
}) => RustLib.instance.api.crateApiKeyPackagesSignEvent(
  nsec: nsec,
  unsignedEventJson: unsignedEventJson,
);

class KeyPackageEventData {
  final String content;
  final List<List<String>> tags30443;
  final List<List<String>> tags443;
  final String dTag;
  final Uint8List hashRef;

  const KeyPackageEventData({
    required this.content,
    required this.tags30443,
    required this.tags443,
    required this.dTag,
    required this.hashRef,
  });

  @override
  int get hashCode =>
      content.hashCode ^
      tags30443.hashCode ^
      tags443.hashCode ^
      dTag.hashCode ^
      hashRef.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPackageEventData &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          tags30443 == other.tags30443 &&
          tags443 == other.tags443 &&
          dTag == other.dTag &&
          hashRef == other.hashRef;
}
