// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<EncryptedMediaOutput> encryptMedia({
  required String dbPath,
  required String groupId,
  required List<int> data,
  required String mimeType,
  required String filename,
}) => RustLib.instance.api.crateApiMediaEncryptMedia(
  dbPath: dbPath,
  groupId: groupId,
  data: data,
  mimeType: mimeType,
  filename: filename,
);

Future<Uint8List> decryptMedia({
  required String dbPath,
  required String groupId,
  required List<int> encryptedData,
  required MediaRefInput mediaRef,
}) => RustLib.instance.api.crateApiMediaDecryptMedia(
  dbPath: dbPath,
  groupId: groupId,
  encryptedData: encryptedData,
  mediaRef: mediaRef,
);

class EncryptedMediaOutput {
  final Uint8List encryptedData;
  final Uint8List originalHash;
  final Uint8List encryptedHash;
  final String mimeType;
  final String filename;
  final BigInt originalSize;
  final BigInt encryptedSize;
  final Uint8List nonce;
  final String? blurhash;
  final String? thumbhash;
  final int? dimensionsWidth;
  final int? dimensionsHeight;

  const EncryptedMediaOutput({
    required this.encryptedData,
    required this.originalHash,
    required this.encryptedHash,
    required this.mimeType,
    required this.filename,
    required this.originalSize,
    required this.encryptedSize,
    required this.nonce,
    this.blurhash,
    this.thumbhash,
    this.dimensionsWidth,
    this.dimensionsHeight,
  });

  @override
  int get hashCode =>
      encryptedData.hashCode ^
      originalHash.hashCode ^
      encryptedHash.hashCode ^
      mimeType.hashCode ^
      filename.hashCode ^
      originalSize.hashCode ^
      encryptedSize.hashCode ^
      nonce.hashCode ^
      blurhash.hashCode ^
      thumbhash.hashCode ^
      dimensionsWidth.hashCode ^
      dimensionsHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptedMediaOutput &&
          runtimeType == other.runtimeType &&
          encryptedData == other.encryptedData &&
          originalHash == other.originalHash &&
          encryptedHash == other.encryptedHash &&
          mimeType == other.mimeType &&
          filename == other.filename &&
          originalSize == other.originalSize &&
          encryptedSize == other.encryptedSize &&
          nonce == other.nonce &&
          blurhash == other.blurhash &&
          thumbhash == other.thumbhash &&
          dimensionsWidth == other.dimensionsWidth &&
          dimensionsHeight == other.dimensionsHeight;
}

class MediaRefInput {
  final String url;
  final Uint8List originalHash;
  final String mimeType;
  final String filename;
  final String schemeVersion;
  final Uint8List nonce;

  const MediaRefInput({
    required this.url,
    required this.originalHash,
    required this.mimeType,
    required this.filename,
    required this.schemeVersion,
    required this.nonce,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      originalHash.hashCode ^
      mimeType.hashCode ^
      filename.hashCode ^
      schemeVersion.hashCode ^
      nonce.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaRefInput &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          originalHash == other.originalHash &&
          mimeType == other.mimeType &&
          filename == other.filename &&
          schemeVersion == other.schemeVersion &&
          nonce == other.nonce;
}
