// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `message_dto`

/// Build an unsigned kind-9 rumor. Pass [content_type] (e.g. "application/json")
/// to tag the payload — the receiver will see it in [MarmotMessage.contentType] and
/// [MarmotMessage.payloadJson] instead of [MarmotMessage.text].
Future<String> buildUnsignedRumor({
  required String npub,
  required String content,
  String? contentType,
}) => RustLib.instance.api.crateApiMessagesBuildUnsignedRumor(
  npub: npub,
  content: content,
  contentType: contentType,
);

Future<String> buildMediaRumor({
  required String dbPath,
  required String npub,
  required String groupId,
  required String caption,
  required String url,
  required List<int> originalHash,
  required String mimeType,
  required String filename,
  required List<int> nonce,
  String? blurhash,
  String? thumbhash,
  int? dimensionsWidth,
  int? dimensionsHeight,
}) => RustLib.instance.api.crateApiMessagesBuildMediaRumor(
  dbPath: dbPath,
  npub: npub,
  groupId: groupId,
  caption: caption,
  url: url,
  originalHash: originalHash,
  mimeType: mimeType,
  filename: filename,
  nonce: nonce,
  blurhash: blurhash,
  thumbhash: thumbhash,
  dimensionsWidth: dimensionsWidth,
  dimensionsHeight: dimensionsHeight,
);

Future<String> send({
  required String dbPath,
  required String unsignedRumorJson,
  required String groupId,
}) => RustLib.instance.api.crateApiMessagesSend(
  dbPath: dbPath,
  unsignedRumorJson: unsignedRumorJson,
  groupId: groupId,
);

Future<MarmotMessage?> processIncoming({
  required String dbPath,
  required String nostrEventJson,
}) => RustLib.instance.api.crateApiMessagesProcessIncoming(
  dbPath: dbPath,
  nostrEventJson: nostrEventJson,
);

/// List messages for a group, newest first. Paginate with [MessageListParams].
Future<List<MarmotMessage>> getMessages({
  required String dbPath,
  required String groupId,
  MessageListParams? params,
}) => RustLib.instance.api.crateApiMessagesGetMessages(
  dbPath: dbPath,
  groupId: groupId,
  params: params,
);

/// Look up a single stored message by Nostr event ID hex.
Future<MarmotMessage?> getMessage({
  required String dbPath,
  required String groupId,
  required String eventIdHex,
}) => RustLib.instance.api.crateApiMessagesGetMessage(
  dbPath: dbPath,
  groupId: groupId,
  eventIdHex: eventIdHex,
);

/// Return the most recent message in a group, or None if empty.
Future<MarmotMessage?> getLastMessage({
  required String dbPath,
  required String groupId,
}) => RustLib.instance.api.crateApiMessagesGetLastMessage(
  dbPath: dbPath,
  groupId: groupId,
);

class MarmotMediaRef {
  final String url;
  final Uint8List originalHash;
  final String mimeType;
  final String filename;
  final String schemeVersion;
  final Uint8List nonce;
  final int? dimensionsWidth;
  final int? dimensionsHeight;

  const MarmotMediaRef({
    required this.url,
    required this.originalHash,
    required this.mimeType,
    required this.filename,
    required this.schemeVersion,
    required this.nonce,
    this.dimensionsWidth,
    this.dimensionsHeight,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      originalHash.hashCode ^
      mimeType.hashCode ^
      filename.hashCode ^
      schemeVersion.hashCode ^
      nonce.hashCode ^
      dimensionsWidth.hashCode ^
      dimensionsHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarmotMediaRef &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          originalHash == other.originalHash &&
          mimeType == other.mimeType &&
          filename == other.filename &&
          schemeVersion == other.schemeVersion &&
          nonce == other.nonce &&
          dimensionsWidth == other.dimensionsWidth &&
          dimensionsHeight == other.dimensionsHeight;
}

class MarmotMessage {
  final String id;
  final String groupId;
  final String senderNpub;
  final String? text;
  final String? contentType;
  final String? payloadJson;
  final PlatformInt64 timestampSecs;
  final List<MarmotMediaRef> media;

  const MarmotMessage({
    required this.id,
    required this.groupId,
    required this.senderNpub,
    this.text,
    this.contentType,
    this.payloadJson,
    required this.timestampSecs,
    required this.media,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      groupId.hashCode ^
      senderNpub.hashCode ^
      text.hashCode ^
      contentType.hashCode ^
      payloadJson.hashCode ^
      timestampSecs.hashCode ^
      media.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarmotMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          groupId == other.groupId &&
          senderNpub == other.senderNpub &&
          text == other.text &&
          contentType == other.contentType &&
          payloadJson == other.payloadJson &&
          timestampSecs == other.timestampSecs &&
          media == other.media;
}

class MessageListParams {
  final int? limit;
  final int? offset;
  final bool? sortByProcessedAt;

  const MessageListParams({this.limit, this.offset, this.sortByProcessedAt});

  @override
  int get hashCode =>
      limit.hashCode ^ offset.hashCode ^ sortByProcessedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageListParams &&
          runtimeType == other.runtimeType &&
          limit == other.limit &&
          offset == other.offset &&
          sortByProcessedAt == other.sortByProcessedAt;
}
